spring:
  application:
    name: producer-api

cloud:
  aws:
    credentials:
      accessKey: # access-key 를 쓸 경우 기입
      secretKey: # secret-key 를 쓸 경우 기입
      use-default-aws-credentials-chain: true
    region:
      static: ap-northeast-2 # 서울 리전이면 ap-northeast-2
    stack:
      auto: false

sqs:
  fifo.queue:
    url: # AWS FIFO Queue URL을 기입
    message:
      group.id: sample
  queue:
    url: # AWS Queue URL을 기입
